### ISSUE TITLE
I am getting the Error for #if __cplusplus < 201103L error

### ISSUE THREAD

**Issue by karadi2016** [joeydubs/cpp-rpg-playground-v1.0#1]
Hi,

I am also new to C++. I was trying to run your game but came across the error from the c++_wsarning.h for  #if __cplusplus < 201103L.

I use CodeBlock IDE and using mingw32-g++.exe for the compiler

Can you help me.
![Uploading Pic.jpg…]()

**Comment by joeydubs** [comment]
Interesting! I am on a Mac, I've been writing the code in Text Edit and compiling in Terminal.
Just googled, it looks as though you may need to check your compiler version and perhaps add something like -std=c++11 to the compile line (if it is command based, I have to add this as well).

http://stackoverflow.com/a/16144116/4635216

Also, the file at the bottom labeled 'project' is the executable that I compiled. I'm not sure if it will run for you though.
